### ISSUE TITLE
Property 'configuration' is missing an input or output annotation.

### ISSUE THREAD

**Issue by robbysmeticapps** [Chimerapps/icapps-translations-gradle-plugin#5]
After updating our project to Gradle 7 we get the following error:

```
A problem was found with the configuration of task ':app:updateDefaulticappsTranslations' (type 'UpdateTranslationsTask').
  - Type 'com.chimerapps.gradle.icapps_translations.UpdateTranslationsTask' property 'configuration' is missing an input or output annotation.
```
I think the configuration property here https://github.com/Chimerapps/icapps-translations-gradle-plugin/blob/master/src/main/java/com/chimerapps/gradle/icapps_translations/UpdateTranslationsTask.kt should be marked with @Internal or @Input

https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem.

**Comment by NicolaVerbeeck** [comment]
Version 1.2.0 has been pushed to maven central. This should fix the issue
